### ISSUE TITLE
Compared with sess

### ISSUE THREAD

**Issue by czy341181** [THU17cyz/3DIoUMatch#2]
Congratulation! a good paper!  

I want to ask the difference between SESS and this paper. Does SESS have no pseudo-label mechanism? But this paper first introduces the filtering module of pseudo-label mechanism, and then adds an IOU module? 
Is my understanding correct？

**Comment by yezhen17** [comment]
Thanks, @czy341181, I think your understanding is correct.

Strictly speaking, SESS has no such mechanism, which you can check in the paper or [code](https://github.com/Na-Z/sess). In a word, SESS enforces a set of consistency losses to **all** predicted bounding boxes. However, you can also view the raw outputs of the teacher network in SESS as some kind of pseudo-label. Then the pseudo-labels are not standard because they are different from the format of ground truth labels. That's why I say SESS has no pseudo-label mechanism strictly speaking.

Yes, our paper introduces the filtering (and deduplication) of pseudo-labels, and then we find only filtering based on classification and objectness is not good enough because we ignore the localization confidence. As a solution, we design an IoU module.
