### ISSUE TITLE
Error occurred when remove_empty_box. 

### ISSUE THREAD

**Issue by czy341181** [THU17cyz/3DIoUMatch#4]
In the inference phase, there is a step before nms that needs to remove 128 proposals with few points, 

but when I get the data like 001333, because this data is special like a face and there is no gt in the whole scene. causing all my boxes to be removed in this step, thus causing errors. Have you met a similar error?

![d14bd1535b1dcee044a1106881014c6](https://user-images.githubusercontent.com/45028386/114365160-c5ca9400-9bac-11eb-9692-b47ccc97cf31.png)
![301cba4ffec7e9b82f2896f84d97fea](https://user-images.githubusercontent.com/45028386/114365236-da0e9100-9bac-11eb-8049-17727dd6bb95.jpg)
![e196aaf9ac3f042f57ee3936e4b9bc8](https://user-images.githubusercontent.com/45028386/114365246-dbd85480-9bac-11eb-93e2-cb8069e190a0.png)

**Comment by czy341181** [comment]
Removing this remove_empty_box module directly should not have much effect on the results, right?

**Comment by yezhen17** [comment]
Hi @czy341181 ,

I have not met with this problem because I always set `remove_empty_box` in `config_dict` to be `False` [here](https://github.com/THU17cyz/3DIoUMatch/blob/ce62f38fc54a278ffaa3ce8845fe0557dcd2a723/train.py#L261), which is by default. I believe you can simply ignore this, because VoteNet also sets this to `False`.

**Comment by czy341181** [comment]
Ok, Thanks for your timely reply!  
By the way,
I noticed that sess only trained 120 epochs, but 3DIoUmatching trained 1001, is this because IoU is hard to train?

**Comment by yezhen17** [comment]
Well, I don't think it's because IoU is hard to train. It seems to me that the pseudo labels need a longer training schedule to reach a high quality, and then the student can effectively learn from the pseudo labels.

By the way, we also tried training SESS with the same schedule as ours, but the performance did not exceed the original performance.

**Comment by czy341181** [comment]
Yes, I also try setting the threshold on SESS to select high quality proposal, the same training time is not as good as before.
So, a longer training schedule will improve performance?

**Comment by yezhen17** [comment]
> Yes, I also try setting the threshold on SESS to select high quality proposal, the same training time is not as good as before.
> So, a longer training schedule will improve performance?

I'm not sure about how will SESS behave after setting a threshold, but I think you can take a try to lengthen the training schedule.

**Comment by czy341181** [comment]
Thanks , I have no problem
